name: Deploy

on:
  push:
    branches:
      - master
      # TODO: remove this
      - multiarch
  schedule:
    # cron every week on monday
    - cron: "0 0 * * 1"

jobs:
  build:
    strategy:
      matrix:
        image:
          - name: python3.11
            python_version: "3.11"
          - name: python3.10
            python_version: "3.10"
          - name: python3.9
            python_version: "3.9"
          - name: python3.8
            python_version: "3.8"
          - name: python3.7
            python_version: "3.7"
          - name: python3.11-slim
            python_version: "3.11"
          - name: python3.10-slim
            python_version: "3.10"
          - name: python3.9-slim
            python_version: "3.9"
          - name: python3.8-slim
            python_version: "3.8"
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get date for tags
        run: echo "DATE_TAG=$(date -I)" >> "$GITHUB_ENV"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          # TODO: remove debug
          tags: |
            tiangolo/uvicorn-gunicorn:${{ matrix.image.name }}-debug
            tiangolo/uvicorn-gunicorn:${{ matrix.image.name }}-debug-${{ env.DATE_TAG }} 
          context: ./docker-images/
          file: ./docker-images/${{ matrix.image.name }}.dockerfile
      - name: Build and push latest
        if: matrix.image.name == 'python3.11'
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: tiangolo/uvicorn-gunicorn:latest-debug
          context: ./docker-images/
          file: ./docker-images/${{ matrix.image.name }}.dockerfile
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: tiangolo/uvicorn-gunicorn
